# Generated by Django 3.1.7 on 2021-04-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('JudgeId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('NoShow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('TableId', models.IntegerField(null=True)),
                ('Description', models.CharField(max_length=1000, null=True)),
                ('ProjectTitle', models.CharField(max_length=500)),
                ('ProjectCategory', models.CharField(max_length=100)),
                ('AvgScore', models.FloatField(null=True)),
                ('Rank', models.IntegerField(null=True)),
                ('Zscore', models.FloatField(null=True)),
                ('ZscoreRank', models.IntegerField(null=True)),
                ('Avg_01', models.FloatField(null=True)),
                ('Avg_01Rank', models.IntegerField(null=True)),
                ('ScaledScore', models.FloatField(null=True)),
                ('ScaledRank', models.FloatField(null=True)),
                ('Scaledz', models.FloatField(null=True)),
                ('IsefScore', models.FloatField(null=True)),
                ('IsefRank', models.IntegerField(null=True)),
                ('CategoryRank', models.IntegerField(null=True)),
                ('FairRank', models.IntegerField(null=True)),
                ('NoShow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('School', models.CharField(max_length=100)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('JaId', models.IntegerField(primary_key=True, serialize=False)),
                ('GoalScore', models.IntegerField(null=True)),
                ('PlanScore', models.IntegerField(null=True)),
                ('ActionScore', models.IntegerField(null=True)),
                ('ResultAnalysisScore', models.IntegerField(null=True)),
                ('CommunicationScore', models.IntegerField(null=True)),
                ('RawScore', models.IntegerField(null=True)),
                ('Zscore', models.FloatField(null=True)),
                ('Rank', models.FloatField(null=True)),
                ('JudgeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.judge')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.project')),
            ],
        ),
    ]
